# Generated by Django 5.2.1 on 2025-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='cashout_status',
            field=models.CharField(choices=[('None', 'No Request'), ('Requested', 'Requested'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='None', max_length=50),
        ),
    ]
