# Generated by Django 5.2.1 on 2025-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_program', '0002_promoter_cashout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='tier',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Partener', 'Partner'), ('VIP Partner', 'VIP Partner')], default='Tier 1', max_length=50),
        ),
    ]
