# Generated by Django 5.2.1 on 2025-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_program', '0003_alter_promoter_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='tier',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Partener', 'Partner'), ('VIP Partner', 'VIP Partner')], default='Tier 1', max_length=50),
        ),
    ]
