# Generated by Django 5.2.1 on 2025-07-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_program', '0004_alter_promoter_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='tier',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('VIP Partner', 'VIP Partner')], default='Tier 1', max_length=50),
        ),
    ]
