# Generated by Django 5.2.1 on 2025-05-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate_program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='no category', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('tour_option', models.CharField(blank=True, choices=[('City Tour', 'City Tour'), ('Historical Tour', 'Historical Tour'), ('Cultural Tour', 'Cultural Tour'), ('Adventure / Hiking Tour', 'Adventure / Hiking Tour'), ('Experiences / Ural Tour', 'Experiences / Ural Tour'), ('Customized Tour', 'Customized Tour'), ('', 'No Tour')], default='', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('rewarded', models.BooleanField(default=False)),
                ('ref_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate_program.code')),
                ('selected_services', models.ManyToManyField(related_name='clients', to='main.service')),
            ],
        ),
    ]
