# Generated by Django 5.2.1 on 2025-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='client',
            name='selected_services',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
