# Generated by Django 5.2.1 on 2025-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_client_selected_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='client',
            name='custom_request',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
